/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function ChillGuy(props) {
  const { nodes, materials } = useGLTF("/chillguy.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane002.geometry}
        material={materials.skin}
        position={[0, 0, 0.729]}
        scale={[1, 1, 0.467]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane001_1.geometry}
        material={materials.Material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane001_2.geometry}
        material={materials.nose}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane001_3.geometry}
        material={materials.skin}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane001_4.geometry}
        material={materials.clothe}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane001_5.geometry}
        material={materials.pants}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane001_6.geometry}
        material={materials.pants2}
      />
    </group>
  );
}

useGLTF.preload("/chillguy.glb");
